version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: portal_db
    restart: always
    environment:
      # Ahora lee del .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./api
    container_name: portal_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      # CONSTRUIMOS LA URL DINÁMICAMENTE PARA DOCKER
      # Usamos el servicio "db" en lugar de localhost
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      # Variables de seguridad leídas del .env
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}

      # Credenciales para el Admin inicial
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

volumes:
  postgres_data: